### ISSUE TITLE
Realtime API call 

### ISSUE THREAD

**Issue by zakrzus** [webqit/realdom#1]
Hi!

How to call Realtime module?

Realtime API seems to be undefined after calling

**Comment by ox-harris** [comment]
Hi @zakrzus , I apologize for replying this late. Work was underway to revamp the library and I didn't do a good job at managing breaking changes. Work is now complete on this and @webqit/dom is now @webqit/realdom, with major API changes. Do check the README for the new API.

Let me know if there's something else I can help with. Cheers.

**Comment by zakrzus** [comment]
@ox-harris thank you :) 

Another problem, when i try to run it with webpack. Have you tested it yet with webpack?

**Comment by ox-harris** [comment]
Damn! Do share the details 

Esbuild is what I've used so far.

**Comment by zakrzus** [comment]
Hi,

In this section:
![err](https://user-images.githubusercontent.com/26283879/229079502-a21a027c-1a90-43c3-abcb-90b643e9ceef.png)
/src/Scheduler.js


I've tried on different targets.

**Comment by ox-harris** [comment]
Hi @zakrzus , thanks for the details. THis has now been fixed. See commit above.

**Comment by zakrzus** [comment]
Now everything is fine! Thank's @ox-harris !
