### ISSUE TITLE
How synchronous observation of the DOM works

### ISSUE THREAD

**Issue by trusktr** [webqit/realdom#2]
Hello! What strategy did you use for synchronous/intercept observation? Did you patch DOM APIs, f.e. so that `append()` will run an intercept callback on the node before it is actually appended, etc?

Perhaps you can explain here while linking to pieces of the code.

I think this might come in handy for solving all the observation problems I've had (f.e. [`MutationObserver` reactions being in the wrong order (per the spec!)](https://github.com/whatwg/dom/issues/1111)).

One thing I want to do is observe every possible mutation in the DOM that could cause an element's computed style to be updated.

We could implement this with it:

- https://github.com/w3c/csswg-drafts/issues/8982

Once we have something nice in place, I want to map computed style to my elements' WebGL features, by reading changes to custom CSS properties that have changed. The feature is described here, along with a rough game plan:

- https://github.com/lume/lume/issues/159

**Comment by trusktr** [comment]
Ah yeah, I see you've patched the APIs here:

https://github.com/webqit/realdom/blob/a9d57db43253f6a5a789ceb621952c899a8e27ae/src/realtime/DOMRealtime.js#L366C10-L366C10

**Comment by ox-harris** [comment]
Ah yeah. (And a message is logged to the console to that effect. 😃)

BTW You have an interesting use case up there.
